package io.github.jjelliott.progsdump;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class FgdAppendingEntityDefinitionBuilder extends EntityDefinitionBuilder {

    File fgd;

    FgdAppendingEntityDefinitionBuilder(File file, File fgd) throws IOException {
        super(file);
        this.fgd = fgd;
    }

    @Override
    protected void addFgd() {
        var fgdString = "///// Autogenerated FGD Entry /////" + System.lineSeparator();
        fgdString += makeFgdEntry();
        fgdString += "///// End Autogenerated FGD Entry /////" + System.lineSeparator();

        try {
            FileWriter fw = new FileWriter(fgd, true);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.newLine();
            bw.write(fgdString);
            bw.newLine();
            bw.close();
        } catch (IOException e) {
            System.out.println("Unable to write to FGD.");
            e.printStackTrace();
        }
    }
}
